### ISSUE TITLE
how to obfuscate getopt arguments

### ISSUE THREAD

**Issue by pete111** [JdeH/Opy#6]
Hello, 
I have this code (python 2.7) but I am not able to successfully obfuscate it. Any idea?

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from pprint import pprint
import sys
import getopt
argv=sys.argv[1:]
opts, args = getopt.getopt(argv, "hg:d") 
print str(int(args[0])*2+int(args[1])*2)
```

**Comment by JdeH** [comment]
Hi

The problem here is that all the identifiers in this program are also occuring in the external modules you import, namely ppoint, sys and getopt.

Since external modules (modules that are not part of your source code directory tree) are not obfuscated, their identifiers also cannot be obfuscated.

So by setting

	external_modules = '''
	pprint
	sys
	getopt
	'''
and

        obfuscate_strings = False

in opy_config.txt, in fact nothing is obfuscated.

Obfuscation only works if you have unique identifiers in your own source code tree that do not all occur also in exernal libraries.

Kind regards
Jacques
