### ISSUE TITLE
'#' in string causes python syntax error

### ISSUE THREAD

**Issue by r2qokk** [JdeH/Opy#8]
In opy_config.txt, I stated my module name as you suggested, and I wrote a usage function that prints out the usage when any invalid parameter given, in which I state the module name again.
However, while Opy obfuscates my script, the module name is reserved and this reservation makes the  string ill-formed.
Python gets error running the ill-formed obfuscated script.

Is this a bug, or an intended behavior?

--Update
```python
print("test.here #hey")
```
becomes
```python
print("test.here 
```
and these are fine
```python
" '' "
```
```python
' "" '
```
```python
""" '' """
```
```python
''' "" '''
```

**Comment by r2qokk** [comment]
```
def usage():
   print "agent.py <working_area> <cirrus_id>  # cirrus agent"
   print "agent.py <working_area> <cirrus_id>  # sut agent"
   print "agent.py                             # simple agent for testing"
   exit(0)

```
becomes
```
def l1lll11l111_opy_():
   print l1ll11_opy_ (u"ࠦࡦ࡭ࡥ࡯ࡶ࠱ࡴࡾࠦ࠼ࡸࡱࡵ࡯࡮ࡴࡧࡠࡣࡵࡩࡦࡄࠠ࠽ࡥ࡬ࡶࡷࡻࡳࡠ࡫ࡧࡂࠥࠦࠊࠡࠢࠣࡴࡷ࡯࡮ࡵࠢࠥࠀ")agent.l111l11111_opy_ <l1ll111_opy_> <l11l11_opy_>

```
and it messed up with the code behind it

**Comment by r2qokk** [comment]
I found this situation is actually quite complicated.
Could we just fix pound signs in one quotation mark pairs(' ', " ")?

**Comment by JdeH** [comment]
Hi,

Since Opy does'nt really parse your source, but rather uses regular expressions, the following syntax limitations hold:

- A comment after a string literal should be preceded by whitespace.
- A ' or " inside a string literal should be escaped with \ rather then doubled.
- A # in a string literal can only be used at the start, so use 'p''#''r' rather than 'p#r'.

The trick is to make # appear only at the start of a string literal.
A general way to do that is splitting your string literals as follows:

`print("test.here #hey")`

 should be written as become:

`print("test.here ""#""hey")`

actually printing the concatenation of three strings, namely:

`"test.here ", "#" and "hey"`

Or, with single quotes if you prefer them:

`print('test.here ''#''hey')`

(Note that there are no double quotes here, '' are two single quotes)

actually again printing the concatenation of three strings, namely:

`'test.here ', '#' and 'hey'`

Hope this helps.

Kind regards
Jacques

**Comment by r2qokk** [comment]
It seems this is the easiest way to have jobs done.
Thanks!

**Comment by JdeH** [comment]
Glad that it worked for you!
